export {
  applyAdd,
  applyDrop,
  assertScopeId,
  computeMembers,
  countByType,
  countItemsByMod,
  DEFAULT_MEMBERS_LIMIT,
  groupMembers,
  modOfNode,
  SCOPE_ID_PATTERN,
  sliceMembers,
  visibleNearMisses,
  type EditSets,
  type MemberCounts,
} from './compute';

export {
  addToScope,
  createScope,
  dropFromScope,
  ensureScopeTables,
  listScopes,
  loadItemIconBase64,
  recomputeScope,
  resetScopeTableCache,
  reviewScope,
  SCOPE_SOURCE,
  showScope,
  type ScopeCreateInput,
  type ScopeShowOptions,
  type ScopeSummary,
  type ScopeView,
} from './store';
